### ISSUE TITLE
client.py > error: unpack requires a string argument of length 2

### ISSUE THREAD

**Issue by kenvernaillenvub** [eclipse/paho.mqtt.python#103]
When running MQTT V3.1 in python on Raspbian Jessie Lite, 
I get the following error. Please help :confused: 

Exception in thread Thread-1:
Traceback (most recent call last):
 File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
   self.run()
 File "/usr/lib/python2.7/threading.py", line 763, in run
   self.__target(_self.__args, *_self.__kwargs)
 File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2580, in _thread_main
   self.loop_forever(retry_first_connection=True)
 File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1378, in loop_forever
   rc = self.loop(timeout, max_packets)
 File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 897, in loop
   rc = self.loop_read(max_packets)
 File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1177, in loop_read
   rc = self._packet_read()
 File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1766, in _packet_read
   rc = self._packet_handle()
 File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2235, in _packet_handle
   return self._handle_pubackcomp("PUBACK")
 File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2542, in _handle_pubackcomp
   mid = struct.unpack("!H", self._in_packet['packet'])
error: unpack requires a string argument of length 2

**Comment by yoch** [comment]
This is a bit strange, because `self._in_packet['packet']` [should have](https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L2539) a length of 2 for PUBACK, as defined by the protocol.

More information on the problem would be helpful (which broker you use, relevant part of appication code, maybe a tcp dump, etc.).

**Comment by kenvernaillenvub** [comment]
seems like the error was thrown because I tried to connect to the server on a port for websockets.

**Comment by JockDaRock** [comment]
I am having this same issue...

```
{ "light-on": true }
{ "light-on": true }
{ "light-on": true }
{ "light-on": true }
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2606, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1470, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 995, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1273, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1838, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2281, in _packet_handle
    return self._handle_pubackcomp("PUBACK")
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2570, in _handle_pubackcomp
    mid, = struct.unpack("!H", self._in_packet['packet'])
struct.error: unpack requires a bytes object of length 2
```

I am running this client on a Docker container.  Linux OS is Alpine on Python 3.6.2.

**Comment by PierreF** [comment]
Pretty sure it's more or less the same issue: you are not talking to an MQTT broker... or at least a mismatch  with the transport (plain vs websocket vs tls).

Now have such traceback is not the best, there is a check that for the length which return MQTT_ERR_PROTOCOL if it's not 2 bytes, but this check is disabled by a _strict_protocol flag to false.
I think this flag should be changed to True (maybe dropping the IF and always doing the check).
At very least in this case either the check should always be performed OR taking explicitly only 2 bytes should be done. Not doing so guarantee to raise an exception since struct.unpack always require the exact size.

**Comment by PierreF** [comment]
Committed a change to be more strict on the protocol. Now instead of raise this exception, the client will disconnect since the broker is using the wrong protocol.

**Comment by Hamelina** [comment]
Hi there, I am having the same issue as @JockDaRock , I am running a programm in a docker container. The programm normaly receives message from a mqtt broker and when the message arrives, a value is stored in redis (also running on a Docker container). Any idea to solve the problem ? 
Thanks in advance
