### ISSUE TITLE
UnboundLocalError when websocket connection is closed immediately

### ISSUE THREAD

**Issue by michaelboulton** [eclipse/paho.mqtt.python#126]
When a websocket connection is closed immediately I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run 
    self.__target(*self.__args, **self.__kwargs)
  File "/home/michael/.virtualenvs/dev/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2557, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/michael/.virtualenvs/dev/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1382, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/michael/.virtualenvs/dev/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 901, in loop
    rc = self.loop_read(max_packets)
  File "/home/michael/.virtualenvs/dev/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1181, in loop_read
    rc = self._packet_read()
  File "/home/michael/.virtualenvs/dev/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1678, in _packet_read
    command = self._ssl.read(1)
  File "/home/michael/.virtualenvs/dev/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2906, in read
    return self._recv_impl(length)
  File "/home/michael/.virtualenvs/dev/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2850, in _recv_impl
    frame = self._create_frame(WebsocketWrapper.OPCODE_CONNCLOSE, payload, 0)
UnboundLocalError: local variable 'payload' referenced before assignment
```

It's trivially fixed by adding `payload = ""` to the top of `WebsocketWrapper._recv_impl` - I can make a pull request but it's only a 1 line change!

**Comment by PierreF** [comment]
Issue fixed by pr #130.
