### ISSUE TITLE
loop_forever() Error exit! 

### ISSUE THREAD

**Issue by xk1yan** [eclipse/paho.mqtt.python#155]
self.client.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1378, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 897, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1177, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1766, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2239, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2389, in _handle_publish
    (slen, packet) = struct.unpack(pack_format, self._in_packet['packet'])
struct.error: bad char in struct format

**Comment by pelmeshk0** [comment]
Hello, I came across the same problem. Are there any ideas about cause/sollution to this?

**Comment by PierreF** [comment]
By looking at the code, the only thing that could produce such error is when _in_packet['packet']) has a size < 2.
In this case, the pack_format would be "!H-1" or "!H-2".

But I don't see how this could be possible... at least with a valid MQTT server. From my understanding the only solution to have a len(packet) < 2 at this point, would be to receive an publish packet, where the remaining length field is less than 2 bytes. But since MQTT require that topic name is present and encoded as <length><value>, where <length> is a 2-bytes integer, remaining length of the publish packet must be at least 2.

Could you provide more information about your setup ? Which broker are you using ? Are your publish "special" (like very short topic name, no payload, long topic name or payload) ?

**Comment by pelmeshk0** [comment]
Hello, I tried http://test.mosquitto.org/ test server and everything seems to work ok. It is indeed a problem on the server side. I'll try to see what's wrong there and hopefully give a feedback if anything is found. Thank you for showing me the right direction!

**Comment by swails** [comment]
This can probably be closed?

**Comment by axd1967** [comment]
RabbitMQ + MQTT with a normal topic _sometimes_ triggers this error in `loop_forever()`.
sometimes a simple publish (qos 0) results in TWO on_message() (paho) 
on_log then returns Error: Unrecognised command 0 

```
(venv) ubuntu@dev:~/python/server$ PYTHONPATH=.. python -m cli
log:Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=my_server_id
log:Sending SUBSCRIBE (d0) [('demo_topic', 0)]
res=0 mid=1
log:Sending PUBLISH (d0, q0, r0, m2), 'demo_topic', ... (21 bytes)
 log:Received CONNACK (0, 0)
conn OK
pub: data=None, mid=2
log:Error: Unrecognised command 0
disconn: data=None, r=2
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/python/server/cli.py", line 77, in <module>
    main()
  File "/home/ubuntu/python/server/cli.py", line 66, in main
    run(args, srv)
  File "/home/ubuntu/python/server/cli.py", line 73, in run
    srv.loop_forever()
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1804, in _packet_read
    byte = self._sock.recv(1)
AttributeError: 'NoneType' object has no attribute 'recv'
(venv) ubuntu@dev:~/python/server$ 

```

another: notice the thread error
```
log:Received PUBLISH (d0, q0, r0, m0), 'demo_topic', ...  (18 bytes)
TOPIC: demo_topic:'ffadfasgfsfsdfadad'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2650, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/home/ubuntu/python/server/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2464, in _handle_publish
    (slen, packet) = struct.unpack(pack_format, self._in_packet['packet'])
error: bad char in struct format

log:Sending PINGREQ
```

ubuntu 16.04

**Comment by ayoub-root** [comment]
(mid, packet) = struct.unpack(pack_format, self._in_packet['packet'])

**Comment by fazlicodes** [comment]
@PierreF I'm getting both the errors mentioned above, what should i change in the code to make it work? I'm using Node-red in IBM Cloud

`
import paho.mqtt.client as mqtt
import pickle

MQTT_BROKER = "broker.hivemq.com" #Example : broker.hivemq.com
MQTT_PORT = 1883
MQTT_KEEPALIVE_INTERVAL = 60
MQTT_TOPIC = "testButtonFazli"
MQTT_MSG="Hello World"

fp = open("tsamodel.pkl", 'rb')
model = pickle.load(fp)

def on_connect(mqttc, obj, flags, rc):
    print("rc: " + str(rc))

def on_message(mqttc, obj, msg):
    mqttc.loop_start()
    mess = model.predict(msg.payload)
    y=float(mess.round(decimals=2))
    infot = mqttc.publish("testButtonFazli2", y, qos=2)
    infot.wait_for_publish()

def on_publish(mqttc, obj, mid):
    print("mid: " + str(mid))

def on_subscribe(mqttc, obj, mid, granted_qos):
    print("Subscribed: " + str(mid) + " " + str(granted_qos))

def on_log(mqttc, obj, level, string):
    print(string)

mqttc = mqtt.Client()
mqttc.on_message = on_message
mqttc.on_connect = on_connect
mqttc.on_publish = on_publish
mqttc.on_subscribe = on_subscribe
mqttc.connect(MQTT_BROKER, MQTT_PORT, MQTT_KEEPALIVE_INTERVAL)
mqttc.subscribe(MQTT_TOPIC, 0)
mqttc.loop_forever()
`

**Comment by mxmaxime** [comment]
Hi,

Sometimes I have this error, shouldn't we add a check on `_in_packet['packet'])` length before destructing it?
