### ISSUE TITLE
Package fail to install on python3 with non-UTF8 local

### ISSUE THREAD

**Issue by PierreF** [eclipse/paho.mqtt.python#181]
```
$ LANG=C python3 setup.py --help
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    readme = readme_file.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 12: ordinal not in range(128)
```

**Comment by Nzbuu** [comment]
Is this master or develop?

**Comment by PierreF** [comment]
It's on all branch: master, fixes and develop (bug added in develop, backported to fixes :))
I've pushed a fix (0a27a82)

**Comment by miketran78727** [comment]
@PierreF Please consider a service release soon.  We can't install Python client because of this issue.

**Comment by PierreF** [comment]
@ralight I've pushed a v1.2.3 with a fix for this issue and 3 others. Could you push it on PyPI ?

**Comment by ralight** [comment]
Done!
