### ISSUE TITLE
error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by connect2robiul** [eclipse/paho.mqtt.python#296]
error 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 564, in h                                                                                                                     andle_one_response
    write(b''.join(towrite))
  File "/usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py", line 510, in w                                                                                                                     rite
    wfile.writelines(towrite)
  File "/usr/lib/python2.7/socket.py", line 334, in writelines
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 4                                                                                                                     03, in sendall
    tail += self.send(data[tail:], flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 3                                                                                                                     94, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 3                                                                                                                     81, in _send_loop
    return send_method(data, *args)
error: [Errno 32] Broken pipe

```

**Comment by PierreF** [comment]
The traceback show no code about paho-mqtt. This bug seems opened in the wrong project.
If it's indeed in paho-mqtt bug, feel free to reopen and provide more context. As is, we can't reproduce this bug.
