### ISSUE TITLE
RaspberryPi Zero W Paho-mqtt not working with local host

### ISSUE THREAD

**Issue by ayanez17** [eclipse/paho.mqtt.python#324]
I just set up my rpi zero w. I've been trying to get the following script to work. The script does work in my rpi 3B but for some reason it does not work on the zero w. The script does work when I connect to any other address but "localhost".

Script:
```
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
        client.subscribe("help/hi")

def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect("localhost", 1883, 60)

client.loop_forever()
```
The error I get is:

```
Traceback (most recent call last):
  File "sample_client.py", line 19, in <module>
    client.connect("localhost", 1883, 60)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 768, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 895, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```
When I change `localhost` to `iot.eclipse.org` it works. Any idea what could be going on? Is there anything else I need to install?

More details: `Python 2.7.13`

Contents of pip show paho-mqtt:

```
Name: paho-mqtt
Version: 1.3.1
Summary: MQTT version 3.1.1 client class
Home-page: http://eclipse.org/paho
Author: Roger Light
Author-email: roger@atchoo.org
License: Eclipse Public License v1.0 / Eclipse Distribution License v1.0
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```
Rasbian Version:

```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by ayanez17** [comment]
I wasn't running mosquitto :(
