### ISSUE TITLE
Error "bad char in struct format" on data publish

### ISSUE THREAD

**Issue by monexiao** [eclipse/paho.mqtt.python#352]
```
Traceback (most recent call last):
  File "/opt/test_mqtt/test_mqtt_client.py", line 227, in run
    self.client.loop_forever()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2728, in _handle_publish
    (topic, packet) = struct.unpack(pack_format, packet)
error: bad char in struct format
```

-------------------------------------------------------------------------------------------------------------------
Hello, I am also in front of this issue when publishing data sometimes.
In my code, I create a class extended the mqtt.client, and thread.
In my MAIN THREAD, I init a instance of the class I created and then call the client.loop_forever() in the thread of the instance.
Finally, sometimes some data will be published from MAIN THREAD, and the error sometimes occur on/after publishing.

I do not call loop_forever() and loop() from different threads in the same time.

Can someone help me or give some tip to avoid this issue ?? I appreciate your response. Thanks a lot.

**Comment by PierreF** [comment]
Could it be a due to MQTT broker like in #155 ? What it the MQTT broker you are using and can you try against Mosquitto ?

**Comment by monexiao** [comment]
> Could it be a due to MQTT broker like in #155 ? What it the MQTT broker you are using and can you try against Mosquitto ?

In my case, the issue occur when the client the Mosquitto 1.4.8, it don't seem to happen after the mosquttio upgraded.

**Comment by MattBrittan** [comment]
I'm going to close this because it seems the issue may have been due to an old version of Mosquitto sending an invalid packet (potentially, there have also been changes to this library since which may have addressed the issue). If the issue has reoccurred then please reopen this.
