### ISSUE TITLE
Getting below wee during MQTT IPV6 COMMUNICATION

### ISSUE THREAD

**Issue by sudeepgithub** [eclipse/paho.mqtt.python#357]
[‎1/‎31/‎2019 9:45 AM] Rajendrabhal, Dhruv11: 
reason 0
msg MqttException
loc MqttException
cause java.net.UnknownHostException: [2002
excep MqttException (0) - java.net.UnknownHostException: [2002
at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: [2002
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
	... 1 more

**Comment by vrst37** [comment]
You are in wrong forum. Please go to java forum to ask this question.
Please close this issue.

**Comment by vrst37** [comment]
BTW next time you ask a question, please understand that we need more information.

A very food way of asking a question can be found  [here](https://github.com/eclipse/paho.mqtt.python/issues/365#issue-419050069).
