### ISSUE TITLE
Making my App crash when the App is in Background while trying to connect from Application class

### ISSUE THREAD

**Issue by Sudhakaraks03** [eclipse/paho.mqtt.python#360]
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.customer.delivX/org.eclipse.paho.android.service.MqttService }: app is in background uid UidRecord{8710802 u0a1102 CEM  idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:414)
       at com.customer.delivX.network.MQTTManager.connectMQTTClient(MQTTManager.java:359)
       at com.customer.delivX.network.MQTTManager.createMQttConnection(MQTTManager.java:347)
       at com.customer.delivX.ApplicationManager.connectMqTT(ApplicationManager.java:208)
       at com.customer.delivX.ApplicationManager.onCreate(ApplicationManager.java:123)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
       at android.app.ActivityThread.-wrap1(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by vrst37** [comment]
Please close this issue and ask in the appropriate forum. This is python library for mqtt, not java.
