### ISSUE TITLE
How to fix EE certificate key too weak

### ISSUE THREAD

**Issue by lizhenwei** [eclipse/paho.mqtt.python#399]
HI, this is my code
```

class mqttClient():
    def __init__(self, host, token, port):
        self.host = host
        self.token = token
        self.port = port
        self.client = mqtt.Client()
        self.client.on_connect = self.__on_connect
        self.client.on_messsage = self.__on_message
        self.next_reading = time.time()
        self.client.username_pw_set(self.token)
        self.client.tls_set(ca_certs="C:/Users/Administrator/Downloads/dadbc6ef-c7ab-4119-ab3e-a29753a207c9.cer",tls_version=ssl.PROTOCOL_TLSv1_2)
        self.client.tls_insecure_set(True)
        self.client.connect(self.host, self.port, 60)
```

my consolelog said:
```
D:\lzwprogram\loadtest\venv\Scripts\python.exe D:/lzwprogram/loadtest/load/mqttClient.py
Traceback (most recent call last):
  File "D:/lzwprogram/loadtest/load/mqttClient.py", line 94, in <module>
    client = mqttClient("192.168.0.243", "JqSnehoaXR6lPSiLZHNy", 1883)
  File "D:/lzwprogram/loadtest/load/mqttClient.py", line 27, in __init__
    self.client.connect(self.host, self.port, 60)
  File "D:\lzwprogram\loadtest\venv\lib\site-packages\paho\mqtt\client.py", line 839, in connect
    return self.reconnect()
  File "D:\lzwprogram\loadtest\venv\lib\site-packages\paho\mqtt\client.py", line 994, in reconnect
    sock.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1056)

Process finished with exit code 1
```
can any body tell me .how to fix EE certificate key too weak error

**Comment by lizhenwei** [comment]
make my server  *.jks file from 512bit to 1024bit ,this error disappear

**Comment by resphinas** [comment]
thanks for your sharing~
