### ISSUE TITLE
problem with sending MQTT PUBLISH when using multiprocessing

### ISSUE THREAD

**Issue by gromajus** [eclipse/paho.mqtt.python#424]
Hi!
In my code I am able to send Publish from the main thread, but when I use multiprocessing, the logger shows that the message was published, but the broker doesn't get any message.
The publish result code is zero.

Is it wanted behaviour? Or I am doing something wrong?

**Comment by JarbasAl** [comment]
i am having same issue, workaround was to create a new client before every publish, less than ideal

at very least we need an error code, this was painful to debug

**Comment by victorct-pronto** [comment]
I'm running into this issue today, this affects almost all of the apps, that do not initialize a connection before every publish, apps deployed on gunicorn, etc. Libraries such as the SDKs for AWS.

**Comment by mxmaxime** [comment]
Just got the same issue here... I lost so many hours, now every thread is creating a new client

**Comment by smilife-chocolat** [comment]
I'm experiencing the issue, described here https://github.com/eclipse/paho.mqtt.python/issues/527 

Thank you @schneeemensch, I have found the same workaround (explain in my ticket)

**Comment by smilife-chocolat** [comment]
I am experiencing the same issue and I have found the same workaround as @schneeemensch (explained here https://github.com/eclipse/paho.mqtt.python/issues/527)

Thank you to be part of my comprehension and solution :)

**Comment by greyltc** [comment]
This is definitely still an issue. My workaround has been to put what I wish to publish in to a `multiprocessing.Queqe()` and publish it from outside the process.

**Comment by dachshund-digital** [comment]
Yup, same issue I tripped over today!  Publish fails unless main thread calls it for me as well.

**Comment by ralight** [comment]
@dachshund-digital Could you try with the current `1.6.x` branch? There have been a log of changes related to threading there.

**Comment by dachshund-digital** [comment]
Yes, I will try... sorry for the late reply... did not happen to see this request until now.  Will report back in a few days when I can get the testing done.

**Comment by dachshund-digital** [comment]
I tried to git clone... but only got version 1.5.1?  Not very familiar with git, so how do I pull a specific branch?

**Comment by ralight** [comment]
@dachshund-digital you were doing everything right, but the version number hadn't been updated in the in-development branch. Sorry for the confusion. I actually did that yesterday by chance, but hadn't pushed it. If you now do `git checkout 1.6.x ; git pull` you should have the correct code and be certain about it.

**Comment by dachshund-digital** [comment]
LOL!  What the definition of insanity... Doing the same thing again, and expecting a different result... I was starting to think I was crazy!  OK, so next couple of days should be able to get some testing done.  Will report back then.

**Comment by dachshund-digital** [comment]
As  quick test, I setup multiprocessing processes for the subscribe queue dequeue, and publish dequeue in my project, which handle all the subscribe messages received by the client, and then publishes any results via the client.  These two routines work fine when invoked by the main thread.  But using separate processes to service the same multiprocessing queues via processes, the subscribe logic works fine.  But every publish attempted by the client when it receives a publish request from the dedicated process, returns result code 4.  This is the same behavior with 1.5.x now on 1.6.x.

Since my project is quite complex, I am going to create a simple script and test again.  If that also fails, will publish here applicable details.

**Comment by dachshund-digital** [comment]
A bit more information... my code does not generate any exceptions or errors, no trace back, etc.  The publish request is accepted, the topic and payload are valid, identical to testing with main thread logic, but as noted I always get result code 4, and broker nor and subscribers (say Node Red) receive anything.

**Comment by ralight** [comment]
Thanks, a small(ish) example would be a big help.

**Comment by dachshund-digital** [comment]
Yeah, working on it now... but I still have something odd... I queried the version... and seems my script is still using 1.5.0, see issue [https://github.com/eclipse/paho.mqtt.python/issues/596](url)

**Comment by dachshund-digital** [comment]
Ok, got virtual environment setup, clean copy of Pi OS as well, just because I could.  Updated python to 3.9.6 over Pi OS default of 3.7.3.  Did explicit git clone for branch 1.6.x.  When I run my test script I get the following on the attempt to publish:

` python3.9 __Test.py
Python Version 3.9.6
Paho MQTT Module Version 1.6.0
OnSubscriber Alive
Client <paho.mqtt.client.Client object at 0xb64d7ca0>, Is Connect? False
Wait
OnPublisher Alive
Connect, Client <paho.mqtt.client.Client object at 0xb64d7ca0>, Is Connect? True, Data 'None', Flags '{'session present': 0}', Result '0'
Subscribe, Is Subscribe? True, Topic 'command/test', Id 1, Result 0
Subscribe, Client '<paho.mqtt.client.Client object at 0xb64d7ca0>', Data 'None', Id '1', Quality '(0,)'
Client <paho.mqtt.client.Client object at 0xb64d7ca0>, Is Connect? True
Subscriber, Message '{'topic': 'command/test', 'payload': '1629644326960'}', Client '<paho.mqtt.client.Client object at 0xb64d7ca0>', Topic 'command/test', Payload '1629644326960', Queue 0, Accumulator 1
Test, Client <paho.mqtt.client.Client object at 0xb64d7ca0>, Instance 1, Topic 'command/test', Payload '1629644326960'
Publisher, Message '{'topic': 'command/test', 'payload': {'Instance': 1, 'Data': '1629644326960'}}', Topic 'status/test', Payload '{'Instance': 1, 'Data': '1629644326960'}', Queue 1, Accumulator 1
Subscriber, Message '{'topic': 'command/test', 'payload': '1629644330582'}', Client '<paho.mqtt.client.Client object at 0xb64d7ca0>', Topic 'command/test', Payload '1629644330582', Queue 0, Accumulator 2
Test, Client <paho.mqtt.client.Client object at 0xb64d7ca0>, Instance 2, Topic 'command/test', Payload '1629644330582'
Publish, Result (4, 1)
Exception: Message publish failed: The client is not currently connected. (<class 'RuntimeError'>)
Traceback (most recent call last):
  File "/home/pi/noderedlistener/NodeRedListener/__Test.py", line 326, in OnPublisher
    thePublishOrNot=theResult.is_published()
  File "/home/pi/noderedlistener/lib/python3.9/site-packages/paho_mqtt-1.6.0-py3.9.egg/paho/mqtt/client.py", line 360, in is_published
    raise RuntimeError('Message publish failed: %s' % (error_string(self.rc)))
RuntimeError: Message publish failed: The client is not currently connected.
OnPublisher Not Alive
`

Tne 'OnPublisher' is the multiprocessing process that attempts the actual publish.  The OnSubscriber does the processing of messages the client queues.  So the test logic is MQ client -> SubscribeQueue -> OnSubscriber.  OnSubscriber -> PublishQueue.  Tnen the OnPublisher dequeues any message, and attempts to publish, at which point result is 4, which under 1.6 provides a more descriptive message.

The actual client object is global, the connection is made via the main thread, and OnSubscriber has not issue with this as a separate process.  But OnPublisher as a separate process, apparently cannot see the active connection.

**Comment by dachshund-digital** [comment]
I would publish my code, but it seems to be programmatic in a comment, the formatting goes nuts and ends up unreadable.

**Comment by dachshund-digital** [comment]
FYI... using publish.single(), works.  So my key question stands, why doe the client publish() method fail to see the existing connection established and used by the client for subscribes.

**Comment by dachshund-digital** [comment]
A bit more... I tweaked the code to report more information... such as calling is_connected() just before the attempt to publish, but also, as I pull an subscribe message.  Since the subscribe queue handler and the publish queue handler are both separate processes, calls to the client is_publish() method, both report false from the separate processes, but reports true from the main process, where the original connect was established.  What is very odd is that the subscribe messages are received and my on_message callback fires, but per the documentation it is not under scope of the main thread.  So I am left with the impression that the paho client can't handle, at least the way I have my code designed, cross process scoping.  Because the subscribe handler never actually interacts with the client object connection, no issues.  But since the publish method relies on the establish connection, it fails.

Python Version 3.9.6
Paho MQTT Module Version 1.6.0
OnSubscriber Alive
OnSubcribe Idle
OnPublisher Alive
OnPublish Idle
Wait
OnConnect, Client <paho.mqtt.client.Client object at 0xb650cf70>, Is Connect? True, Data 'None', Flags '{'session present': 0}', Result '0'
Subscribe, Is Subscribe? True, Topic 'command/test', Id 1, Result 0
OnSubscribe, Client '<paho.mqtt.client.Client object at 0xb650cf70>', Data 'None', Id '1', Quality '(0,)'
Client <paho.mqtt.client.Client object at 0xb650cf70>, Is Connect? True
Wait, Client <paho.mqtt.client.Client object at 0xb650cf70>, Is Connect? True
OnSubscriber, Client <paho.mqtt.client.Client object at 0xb650cf70>, Is Connect? False
OnSubscriber, Message '{'topic': 'command/test', 'payload': '1629665379959'}', Client '<paho.mqtt.client.Client object at 0xb650cf70>', Topic 'command/test', Payload '1629665379959', Queue 0, Accumulator 1
OnTest, Client <paho.mqtt.client.Client object at 0xb650cf70>, Is Connect? False, Instance 1, Topic 'command/test', Payload '1629665379959'
OnSubcribe Idle
OnPublisher, Client <paho.mqtt.client.Client object at 0xb650cf70>, Is Connect? False
OnPublisher, Message '{'topic': 'command/test', 'payload': {'Instance': 1, 'Data': '1629665379959'}}', Topic 'status/test', Payload '{'Instance': 1, 'Data': '1629665379959'}', Queue 0, Accumulator 1
OnPublish, Result (4, 1)
OnException: Message publish failed: The client is not currently connected. (<class 'RuntimeError'>)
Traceback (most recent call last):
  File "/home/pi/noderedlistener/NodeRedListener/__Test.py", line 355, in OnPublisher
    thePublishOrNot=theResult.is_published()
  File "/home/pi/noderedlistener/lib/python3.9/site-packages/paho_mqtt-1.6.0-py3.9.egg/paho/mqtt/client.py", line 360, in is_published
    raise RuntimeError('Message publish failed: %s' % (error_string(self.rc)))
RuntimeError: Message publish failed: The client is not currently connected.

**Comment by sakoarts** [comment]
Weird that this still isn't fixed, I'm trying to publish a message in a Flask GET request and it (almost) never works because these request handlers are obviously also in separate threads. It does not seem like a weird use case to me, but because of this bug, it does not work.

**Comment by MattBrittan** [comment]
Tagging as an enhancement as its going to take some time to sort this out (if anyone is willing to help please yell out). I can duplicate the issue with the code provided by @dachshund-digital but suspect this is a design issue (e.g. the library uses `thread.lock` not `multiprocessing.lock` etc) but this is well above my python knowledge!

**Comment by PierreF** [comment]
I doubt sharing a Client() over multiple process is something we can and want to support. The paho Client() can not be made picklable since it contains a socket.

> Picklability
>   Ensure that the arguments to the methods of proxies are picklable.
-- https://docs.python.org/3/library/multiprocessing.html#programming-guidelines

By design, multiprocessing use multiple process which do not share object between them (unless special multiprocessing stuff is used). That means `theClient` can NOT the same between process, from there I don't see how to make this working.

You will have to make you own way to communicate across your processes and have the paho client in a single process.

Comment that talk only about thread are not the same issue at this one, since the issue is sharing between multiple processes. multithreading is supported.
