### ISSUE TITLE
Capture exception: socket.gaierror: [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by zdrux** [eclipse/paho.mqtt.python#478]
I am trying to build a GUI interface for paho.mqtt, but when I enter an invalid hostname upon client.connect, the app simply exits with the following found in the Python console:

```
Traceback (most recent call last):
  File "C:/Users/zdrux/PycharmProjects/mq/main.py", line 56, in <module>
    client.connect(values[0])  # connect to broker
  File "C:\Users\zdrux\PycharmProjects\mq\lib\site-packages\paho\mqtt\client.py", line 937, in connect
    return self.reconnect()
  File "C:\Users\zdrux\PycharmProjects\mq\lib\site-packages\paho\mqtt\client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "C:\Users\zdrux\PycharmProjects\mq\lib\site-packages\paho\mqtt\client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "C:\Users\zdrux\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\zdrux\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
```

How do I capture this error so my app doesn't forcefully close and I can at least print some error to the user and keep the app running?

**Comment by poleguy** [comment]
It's not obvious why you can't just try: except on it... but it seems to be because the exception is on a different thread. You need to look at the logger callback: .on_log(), and unfortunately you might have to modify the source code as this error isn't caught everywhere it can come up. I'm working on a PR to try to address this.

**Comment by MattBrittan** [comment]
I'm going to close this due to age/inactivity (apologies there was not more of a response years ago!). If you are still seeing this issue with a current version of the library then please feel free to reopen the issue (there have been quite a few changes to exception handling in the interim but I'm sure that some problems remain).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
