### ISSUE TITLE
Error upon receiving keepalive connection

### ISSUE THREAD

**Issue by fcracker79** [eclipse/paho.mqtt.python#488]
I am using paho-mqtt as a subscription client for AWS Appsync notifications.
Sometimes AWS AppSync seems to send `connection: keep-alive` response, which causes the library get into a loop from which it never gets out.

The log is the following:

```
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]: Traceback (most recent call last):
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/client.py", line 1807, in loop_forever
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:     self.reconnect()
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/client.py", line 1108, in reconnect
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:     self._websocket_path, self._websocket_extra_headers)
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/client.py", line 3556, in __init__
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:     self._do_handshake(extra_headers)
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:   File "/home/ubuntu/chattyraspi/lib/python3.6/site-packages/paho/mqtt/client.py", line 3610, in _do_handshake
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]:     "WebSocket handshake error, connection not upgraded: " + str(self._readbuffer))
May 03 11:32:02 ip-10-0-1-121 test_chattyraspi[11317]: paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error, connection not upgraded: bytearray(b'connection: keep-alive\r\n')
```

I have slightly modified the source code of Paho to get more verbose logs on what the receiving buffer string contains.

**Comment by MattBrittan** [comment]
Looks like you got an [answer on stackoverflow](https://stackoverflow.com/a/61605533/11810946) so I'll copy it below and close this issue.

>IoT disconnects WebSocket connection and requires authentication every 24 hours. You will need to redo Subscribe(basically the authentication and connect to the pre-signed URL) every 24 hours.
