### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

### ISSUE THREAD

**Issue by sonastyle** [eclipse/paho.mqtt.python#519]
**#CODE**
import paho.mqtt.client as mqtt
import ssl

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    client.subscribe("$SYS/#")

def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.tls_set(ca_certs=None, certfile=None, keyfile=None, cert_reqs=ssl.CERT_REQUIRED,
     tls_version=ssl.PROTOCOL_TLS, ciphers=None)
client.tls_insecure_set(False)    
    
print("connecting to broker")
client.connect("mqtt.eclipse.org", 8883, 60)

client.loop_forever()

**###### END OF CODE#########**

#OUTPUT
connecting to broker
Traceback (most recent call last):
  File "mqttRaw.py", line 32, in <module>
    client.connect("mqtt.eclipse.org", 8883, 60)
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**########### end of terminal op #######**
**#The same code was running till 10.10.20, and after that its showing this certificate error even if #after fresh installation of raspi sd card**

**Comment by jackattack21** [comment]
I just started with this library. Been running MQTT clients and servers in C for a while. I can't for the life of me get the TLS to verify. There's gotta be an issue with the library right now. Have you gotten it to work?

**Comment by swails** [comment]
I have gotten it to verify.  mqtt.eclipse.org uses let's encrypt as it's signing cert.  Try installing the `certifi` package from PyPI to install an up-to-date root CA trust store.

**Comment by jackattack21** [comment]
Can you post your implementation of certifi and your TLS function call? 

I actually can't even install certifi. Pip is getting an SSL error with that package repository too. 

Maybe not Paho, and it is something to do with my trust store or python 2.7

**Comment by MattBrittan** [comment]
I'm going to close this due to it's age and the face that `mqtt.eclipse.org` is no longer line (cannot resolve the domain). If you have an example using a live server then please feel free to reopen this.
