### ISSUE TITLE
Creating a paho.mqtt.client.Client with invalid client_id and clean_session=False raises an AttributeError on deletion

### ISSUE THREAD

**Issue by chris-hibberd** [eclipse/paho.mqtt.python#520]
For package version paho-mqtt 1.5.1 and Python 3.8.2, running the following code:

``` python
from paho.mqtt.client import Client
try:
    Client(client_id="", clean_session=False)
except ValueError as e:
    print(f"This is handled: {e}")
```

Produces the following output:
```
This is handled: A client id must be provided if clean session is False.
Exception ignored in: <function Client.__del__ at 0x7f4531fab0d0>
Traceback (most recent call last):
  File "/c/Users/hibbe/Code/bg-hub-applications/.venv/lib/python3.8/site-packages/paho/mqtt/client.py", line 660, in __del__
    self._reset_sockets()
  File "/c/Users/hibbe/Code/bg-hub-applications/.venv/lib/python3.8/site-packages/paho/mqtt/client.py", line 704, in _reset_sockets
    self._sock_close()
  File "/c/Users/hibbe/Code/bg-hub-applications/.venv/lib/python3.8/site-packages/paho/mqtt/client.py", line 691, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
```

The error is raised in `_sock_close` when `__del__` is called on the client as _sock_close checks `if not self._sock:` but the `_sock` attribute is never created on the client object as the exception is raised first (from `__init__` of Client in .venv/lib/python3.8/site-packages/paho/mqtt/client.py):
``` python
            if not clean_session and (client_id == "" or client_id is None):
                raise ValueError(
                    'A client id must be provided if clean session is False.')
            self._clean_session = clean_session

        if transport.lower() not in ('websockets', 'tcp'):
            raise ValueError(
                'transport must be "websockets" or "tcp", not %s' % transport)
        self._transport = transport.lower()
        self._protocol = protocol
        self._userdata = userdata
        self._sock = None
```

Perhaps either attribute initialisation should be moved earlier in the constructor, or `_sock_close` should check that the attribute exists.

**Comment by ralight** [comment]
Thanks Chris, and sorry for the delay in getting to this. I've pushed a fix and this will be part of 1.6.0.
