### ISSUE TITLE
AttributeError: module 'paho.mqtt.publish' has no attribute 'single'

### ISSUE THREAD

**Issue by RossGoodman** [eclipse/paho.mqtt.python#548]
I had this working fine for a few days then I got the above error.
To try and troubleshoot I re-installed in a venv

```
(logging) rossgoodmancom@penguin:~/scripts/python/logging$ pip3 list
Package           Version
----------------- -------
astroid           2.4.2  
isort             5.7.0  
lazy-object-proxy 1.4.3  
mccabe            0.6.1  
paho-mqtt         1.5.1  
pip               18.1   
pkg-resources     0.0.0  
psutil            5.8.0  
pylint            2.6.0  
setuptools        40.8.0 
six               1.15.0 
toml              0.10.2 
typed-ast         1.4.2  
wheel             0.36.2 
wrapt             1.12.1 
```

and

```
(logging) rossgoodmancom@penguin:~/scripts/python/logging$ pip3 show paho-mqtt
Name: paho-mqtt
Version: 1.5.1
Summary: MQTT version 5.0/3.1.1 client class
Home-page: http://eclipse.org/paho
Author: Roger Light
Author-email: roger@atchoo.org
License: Eclipse Public License v1.0 / Eclipse Distribution License v1.0
Location: /home/rossgoodmancom/scripts/venv/logging/lib/python3.7/site-packages
Requires: 
Required-by: 
(logging) rossgoodmancom@penguin:~/scripts/python/logging$ 
```

When I run my code

```
#!/usr/bin/env python3

import time
import psutil
import socket
import paho.mqtt.publish as publish

print("""Logging CPU, Memory & Disk

Press Ctrl+C to exit!

""")
the_hostname = socket.gethostname()

try:
    while True:
        cpu_value = psutil.cpu_percent()
        memory_value = psutil.virtual_memory().percent
        disk_pct = psutil.disk_usage('/').percent
        # print('CPU % ', cpu_value)
        # print('Memory % ', memory_value)
        # print('Battery % ', battery_value)
        # print(psutil.disk_usage('/').percent)
        payload='[{"cpu_pct":'+str(cpu_value)+',"memory_pct":'+str(memory_value)+',"disk_pct":'+str(disk_pct)+'},{"hostname":"'+the_hostname+'"}]'
        # print(payload)
        publish.single("hosts/performance", payload, hostname="192.168.1.4", port=1883, retain=False, client_id=the_hostname)
        time.sleep(1.0)
except KeyboardInterrupt:
    print('Logging stopped.')
```

I get the error:

```
Traceback (most recent call last):
  File "./logging.py", line 5, in <module>
    import paho.mqtt.publish as publish
  File "/home/rossgoodmancom/scripts/venv/logging/lib/python3.7/site-packages/paho/mqtt/publish.py", line 29, in <module>
    from . import client as paho
  File "/home/rossgoodmancom/scripts/venv/logging/lib/python3.7/site-packages/paho/mqtt/client.py", line 20, in <module>
    import logging
  File "/home/rossgoodmancom/scripts/python/logging/logging.py", line 25, in <module>
    publish.single("hosts/performance", payload, hostname="192.168.1.4", port=1883, retain=False, client_id=the_hostname)
AttributeError: module 'paho.mqtt.publish' has no attribute 'single'
```

Any thoughts???

**Comment by RossGoodman** [comment]
Edited above to correct the formatting.

**Comment by RossGoodman** [comment]
I can now "fix" this but not sure why it's a problem (new to Python).
The above script was in a folder called "logging" - if I move it to a different folder it works.
Likewise if I take a working copy of publish.py and copy it to a folder called "logging" then it gives the same error as above.

**Comment by seven0fx** [comment]
.../lib/python3.7/site-packages/paho/mqtt/client.py will try to import the module logging and your folder and *.py file is named 'logging'

**Comment by ralight** [comment]
I'm going to close this then as it wasn't a Paho problem. I'm glad you got it sorted.
