### ISSUE TITLE
on_connect() argument call

### ISSUE THREAD

**Issue by ayang629** [eclipse/paho.mqtt.python#55]
When launching a client, the following error shows up (sometimes):

Traceback (most recent call last):
  File "simple_client.py", line 29, in <module>
    client.run()
  File "simple_client.py", line 13, in run
    self.client.loop()
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 811, in loop
    rc = self.loop_read(max_packets)
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 1073, in loop_read
    rc = self._packet_read()
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 1475, in _packet_read
    rc = self._packet_handle()
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 1949, in _packet_handle
    return self._handle_connack()
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 2010, in _handle_connack
    self.on_connect(self, self._userdata, flags_dict, result)
TypeError: on_connect() takes exactly 4 arguments (5 given)

Looking into the source code and the following chunk (line 2005 in /src/paho/mqtt/client.py):

 if argcount == 3:
                self.on_connect(self, self._userdata, result)
            else:
                flags_dict = dict()
                flags_dict['session present'] = flags & 0x01
                self.on_connect(self, self._userdata, flags_dict, result)

Making a self. call inside of a python class adds an additional argument to the function call, effectively making it 4 arguments, not 3. Another suggestion is that the else command should probably be an elif considering any other number of arguments that are not 4 or 5 should produce an error.

**Comment by ralight** [comment]
This should only happen if your callback hasn't got the correct number of arguments. I agree that having an extra argument in the class method isn't ideal, but that's the situation right now. There are other bugs discussing this as well. I'm closing this now because I don't believe it is a bug in the Paho Python client.
