### ISSUE TITLE
Caught exception in on_message: 'NoneType' object has no attribute 'unread_result'

### ISSUE THREAD

**Issue by arslion** [eclipse/paho.mqtt.python#557]
Keep getting this error and code is crashing after one message recieved.
```
Caught exception in on_message: 'NoneType' object has no attribute 'unread_result'
Traceback (most recent call last):
  File "updater.py", line 250, in <module>
    client.loop_forever()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "updater.py", line 218, in on_message
    print cursor.fetchall()
  File "/usr/local/lib/python2.7/site-packages/mysql/connector/cursor_cext.py", line 512, in fetchall
    if not self._cnx.unread_result:
AttributeError: 'NoneType' object has no attribute 'unread_result'
```

**Comment by BertKleewein** [comment]
This isn't a bug in Paho.  It looks like your `on_message` function in updater.py is calling a mysql function (`cursor.fetchall`), and that function is raising an exception.  Maybe `cursor` hasn't be initialized properly?
