### ISSUE TITLE
Wrong on_disconnect() being called for an MQTT v5 connection

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.python#570]
I have an MQTT v5 connection to Mosquitto, which I am trying to shut down cleanly as I exit the program, by calling `disconnect()` on the client. 

I registered a callback for the disconnect as a member of a class, using the form:

```
    def _on_disconnect(self, cli, _userdata, rc, props):
        log.warning("MQTT client '%s' disconnected.", self.name)
```

But it crashes out, as it seems to be calling the v3 version of the callback:

```
Caught exception in on_disconnect: _on_disconnect() missing 1 required positional argument: 'props'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fmp/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/fmp/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/fmp/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1197, in loop
    rc = self.loop_write(max_packets)
  File "/home/fmp/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1598, in loop_write
    rc = self._packet_write()
  File "/home/fmp/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2374, in _packet_write
    self._do_on_disconnect(0)
  File "/home/fmp/.local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3360, in _do_on_disconnect
    self.on_disconnect(self, self._userdata, rc)
TypeError: _on_disconnect() missing 1 required positional argument: 'props'
```

Am I doing something dumb here?

**Comment by ralight** [comment]
Thanks Frank, you're not doing anything dumb - there was an incorrect check. I've fixed that in the `develop` branch if you fancy testing out the fix.
