### ISSUE TITLE
publish/subscribe helper functions break with MQTTv5

### ISSUE THREAD

**Issue by briggySmalls** [eclipse/paho.mqtt.python#575]
# Description

Hello, thanks for this great library. I'd like to report what I believe is a bug.

We are using the MQTTv5 protocol, and recently I attempted to use the synchronous helper functions (in the `paho.mqtt.publish` and `paho.mqtt.subscribe` modules) instead of the asynchronous client (`paho.mqtt.client`).

I found that this would not work using the MQTTv5 protocol version.

#  Steps to reproduce

```
# Start a broker
docker run -d -p 1883:1883 eclipse-mosquitto
# Attempt to send a message
python -c "from paho.mqtt.publish import single; from paho.mqtt.client import MQTTv5; single('test', protocol=MQTTv5)"
```

The following error exhibits:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/publish.py", line 231, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/publish.py", line 168, in multiple
    client.loop_forever()
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/Users/sambriggs/Library/Caches/pypoetry/virtualenvs/e2e-2ZKQCMVw-py3.8/lib/python3.8/site-packages/paho/mqtt/client.py", line 3026, in _handle_connack
    self.on_connect(self, self._userdata,
TypeError: _on_connect() takes 4 positional arguments but 5 were given
```

## Thoughts

Perhaps MQTTv5 was never intended to be supported? In which case I'd suggest a guard against this valid protocol version being supplied, avoiding this cryptic error.

**Comment by ralight** [comment]
@briggySmalls I've added basic support now, so this doesn't raise an exception any more. You can't set properties, but you can recieve them.

@samba The on_connect documentation states:

```
        Expected signature for MQTT v3.1 and v3.1.1 is:
            connect_callback(client, userdata, flags, rc)

        and for MQTT v5.0:
            connect_callback(client, userdata, flags, reasonCode, properties)
```

Sorry that you missed that. I can see why it could happen - there was callback documentation in two places. I've removed some of the duplicate documentation so anybody reading up on callbacks will see that.

**Comment by briggySmalls** [comment]
Thanks @ralight, that’s definitely an improvement. Appreciate you responding to this issue

**Comment by briggySmalls** [comment]
Looking at you commit I notice two things:

- my MR #577 added helper tests to the `tests` directory which should perhaps be removed now I see all the action is in `test/lib`
- perhaps a note in the documentation stating the limitations of the helpers for v5 (cannot set properties) would be useful for users

**Comment by ralight** [comment]
@briggySmalls Done!
