### ISSUE TITLE
Trio example not working with latest trio version

### ISSUE THREAD

**Issue by adiroiban** [eclipse/paho.mqtt.python#678]
Hi,

I am trying to run paho with trio.

I am completely new to paho or trio.

I got a copy paste of the example.

I am using:

* Python 3.10.4  - Ubuntu 22.04
* trio (0.21.0)
* paho (1.6.1)

The traceback

```
python run-trio.py 
Starting
Socket opened
large write request
misc_loop started
Traceback (most recent call last):
  File "/home/adi/chevah/run-trio.py", line 139, in <module>
    trio.run(TrioAsyncMqttExample().main)
  File "/home/adi/chevah/venv/lib/python3.10/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/adi/chevah/run-trio.py", line 129, in main
    async with trio.open_nursery() as nursery:
  File "/home/adi/chevah/venv/lib/python3.10/site-packages/trio/_core/_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "/home/adi/chevah/run-trio.py", line 70, in read_loop
    await trio.hazmat.wait_readable(self.sock)
  File "/home/adi/chevah/venv/lib/python3.10/site-packages/trio/_deprecate.py", line 124, in __getattr__
    raise AttributeError(msg.format(self.__name__, name))
AttributeError: module 'trio' has no attribute 'hazmat'
finished large write
```

It looks like the hazmat was deprecated https://github.com/python-trio/trio/pull/1722

**Comment by adiroiban** [comment]
I think the fix is something like this

```diff
-await trio.hazmat.wait_readable(self.sock)
+await trio.lowlevel.wait_readable(self.sock)
```

I tried it and it looks like it's working
