### ISSUE TITLE
Error：when I use paho.mqtt send message with ssl，some times it would be raise error like this:

### ISSUE THREAD

**Issue by lowmanisbusy** [eclipse/paho.mqtt.python#691]
Traceback (most recent call last):
  File "/app/extensions/mqtt_clients.py", line 344, in another_one_publish
    msg_info = self.client.publish(topic, payload, qos, retain)
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 1257, in publish
    rc = self._send_publish(
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 2693, in _send_publish
    return self._packet_queue(PUBLISH, packet, mid, qos, info)
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 3016, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
  File "/usr/local/lib/python3.8/dist-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 501, in send
    return self._sslobj.write(data)
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2410)

PS: If the payload more bigger (or bad network)，it would be raise more frequently

**Comment by MattBrittan** [comment]
Apologies for the (very) delayed response. Can you please confirm if you are still seeing this and, if so, what version of the library you are using.

**Comment by MattBrittan** [comment]
I'm going to close this as without more info there is little that can be done. It's possible that issue #853 has the same root cause (and there is some more info on that issue - have not traced a root cause at this point so any info you can add to that issue would be helpful).
