### ISSUE TITLE
OSError have no include TimeoutError?

### ISSUE THREAD

**Issue by nanshenwei** [eclipse/paho.mqtt.python#694]
I found this error⬇️
```bash
Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/opt/homebrew/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/opt/homebrew/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/opt/homebrew/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/opt/homebrew/lib/python3.10/site-packages/paho/mqtt/client.py", line 2370, in _packet_read
    command = self._sock_recv(1)
  File "/opt/homebrew/lib/python3.10/site-packages/paho/mqtt/client.py", line 640, in _sock_recv
    return self._sock.recv(bufsize)
TimeoutError: [Errno 60] Operation timed out
```
and check the code:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/40733582/206690972-498c780a-2bbf-469d-a13a-f2d911efc181.png">
```python
class ConnectionError(OSError): ...
```
Looks fine, But it is none.
So I add this code:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/40733582/206691362-9e6394c8-277f-4fea-bb6b-a32d3649ea9d.png">
**It works.**
<img width="791" alt="image" src="https://user-images.githubusercontent.com/40733582/206691542-c6cca4b5-75af-4f42-b023-d98902b350a4.png">

This is not the same as described in the previous issue #291 , why?

**Comment by MattBrittan** [comment]
PR #710 has been (partly!) committed and should resolve this. I'm going to flag the issue as completed (would appreciate confirmation that the issue is resolved).

Note: This is part of an exercise to clean up old issues so that the project can move forwards. Due to the number of issues being worked through mistakes will be made; please feel free to reopen this issue (or comment) if you believe it's been closed in error.
