### ISSUE TITLE
sslv3_alert_bad_record_mac

### ISSUE THREAD

**Issue by yangxiang12** [eclipse/paho.mqtt.python#722]
python version: 3.6.9
sslerror: [ssl: sslv3_alert_bad_record_mac] sslv3 alert bad record mac (_ssl.c:2309)

How should this problem be solved?

**Comment by yangxiang12** [comment]
Exception in thread Thread-2842003:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "paho/mqtt/client.py", line 3591, in _thread_main
  File "paho/mqtt/client.py", line 1756, in loop_forever
  File "paho/mqtt/client.py", line 1164, in _loop
  File "paho/mqtt/client.py", line 1556, in loop_read
  File "paho/mqtt/client.py", line 2370, in _packet_read
  File "paho/mqtt/client.py", line 640, in _sock_recv
  File "ssl.py", line 997, in recv 
  File "ssl.py", line 874, in read
  File "ssl.py", line 633, in read
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2309)

**Comment by MattBrittan** [comment]
Apologies for the long delay in responding.

Sorry - we would need more information (i.e. what broker, broker setup/log, output of `openssl s_client -connect servername:port` etc).  If you have solved this yourself in the interim please close the issue.

**Comment by DeboBurro** [comment]
have similar issue when connecting AWS IoT MQTT broker

Environment:
- paho-mqtt: 2.1.0
- python 3.12.3
- connection port: 8883
- Broker: AWS IoT MQTT broker
- stable internet

Error log
```
Connected to {variable}.iot.{region}.amazonaws.com:8883
Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'{Client_ID}'
Disconnected from {variable}.iot.{region}.amazonaws.com:8883 due to Unspecified error
failed to receive on socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2559)
```
and we connect via 
```
class MQTTClient:
    def __init__(self, endpoint: str, client_id: str, ca_path: str, cert_path: str, key_path: str):
        self.endpoint = endpoint
        self.client_id = client_id
        self.client = mqtt.Client(client_id=client_id, callback_api_version=mqtt.CallbackAPIVersion.VERSION2)
        self.client.tls_set(ca_certs=ca_path, certfile=cert_path, keyfile=key_path, tls_version=ssl.PROTOCOL_TLSv1_2)
        self.client.connect(self.endpoint, port=8883, keepalive=60)
        self.client.loop_start()
```

**Comment by ianstorrs-cd** [comment]
I see the same SSL issue often. Paho 1.6.1 client, connecting / connected to hivemq MQTT broker. I do not have access to broker logs. Sometimes Paho ends up in a loop of on_connect callbacks with no on_disconnect callbacks. And I mean an infinite loop. 

May 12 17:35:35 python3[29330]: Exception in thread Thread-1 (_thread_main):
May 12 17:35:35 python3[29330]: Traceback (most recent call last):
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
May 12 17:35:35 python3[29330]:     self.run()
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/threading.py", line 953, in run
May 12 17:35:35 python3[29330]:     self._target(*self._args, **self._kwargs)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
May 12 17:35:35 python3[29330]:     self.loop_forever(retry_first_connection=True)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
May 12 17:35:35 python3[29330]: devmgmt:1227     - MainThread               - INFO - mqtt: Received PUBCOMP (Mid: 19)
May 12 17:35:35 python3[29330]:     rc = self._loop(timeout)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1181, in _loop
May 12 17:35:35 python3[29330]: devmgmt:1200     - MainThread               - INFO - mqtt: Message (Mid: 19) devmgmt/354513599126954-1aa27f00bfdb-608a10c24009/wirepas published successfully
May 12 17:35:35 python3[29330]:     rc = self.loop_write()
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1577, in loop_write
May 12 17:35:35 python3[29330]: devmgmt:1227     - MainThread               - INFO - mqtt: Sending PUBREL (Mid: 18)
May 12 17:35:35 python3[29330]: devmgmt:1227     - Thread-1 (_thread_main)  - INFO - mqtt: Sending PUBREL (Mid: 19)
May 12 17:35:35 python3[29330]: Exception in thread Thread-1 (_thread_main):
May 12 17:35:35 python3[29330]: Traceback (most recent call last):
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
May 12 17:35:35 python3[29330]:     self.run()
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/threading.py", line 953, in run
May 12 17:35:35 python3[29330]:     self._target(*self._args, **self._kwargs)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
May 12 17:35:35 python3[29330]:     self.loop_forever(retry_first_connection=True)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
May 12 17:35:35 python3[29330]: devmgmt:1227     - MainThread               - INFO - mqtt: Received PUBCOMP (Mid: 19)
May 12 17:35:35 python3[29330]:     rc = self._loop(timeout)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1181, in _loop
May 12 17:35:35 python3[29330]: devmgmt:1200     - MainThread               - INFO - mqtt: Message (Mid: 19) devmgmt/354513599126954-1aa27f00bfdb-608a10c24009/wirepas published successfully
May 12 17:35:35 python3[29330]:     rc = self.loop_write()
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 1577, in loop_write
May 12 17:35:35 python3[29330]:     rc = self._packet_write()
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
May 12 17:35:35 python3[29330]:     write_length = self._sock_send(
May 12 17:35:35 python3[29330]: devmgmt:1551     - MainThread               - ERROR - Exception in MQTT loop_forever: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2578)
May 12 17:35:35 python3[29330]: devmgmt:1552     - MainThread               - INFO - MQTT client state after exception: connected=True, state=1
May 12 17:35:35 python3[29330]: devmgmt:1560     - MainThread               - INFO - Waiting for 5 seconds before restarting loop_forever...
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 649, in _sock_send
May 12 17:35:35 python3[29330]:     return self._sock.send(buf)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/ssl.py", line 1239, in send
May 12 17:35:35 python3[29330]:     return self._sslobj.write(data)
May 12 17:35:35 python3[29330]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)
May 12 17:35:35 python3[29330]:     rc = self._packet_write()
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
May 12 17:35:35 python3[29330]:     write_length = self._sock_send(
May 12 17:35:35 python3[29330]: devmgmt:1551     - MainThread               - ERROR - Exception in MQTT loop_forever: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2578)
May 12 17:35:35 python3[29330]: devmgmt:1552     - MainThread               - INFO - MQTT client state after exception: connected=True, state=1
May 12 17:35:35 python3[29330]: devmgmt:1560     - MainThread               - INFO - Waiting for 5 seconds before restarting loop_forever...
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/site-packages/paho/mqtt/client.py", line 649, in _sock_send
May 12 17:35:35 python3[29330]:     return self._sock.send(buf)
May 12 17:35:35 python3[29330]:   File "/usr/lib/python3.10/ssl.py", line 1239, in send
May 12 17:35:35 python3[29330]:     return self._sslobj.write(data)
May 12 17:35:35 python3[29330]: ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)
May 12 17:35:40 python3[29330]: devmgmt:1562     - MainThread               - INFO - MQTT client state after exception: connected=True, state=1
May 12 17:35:40 python3[29330]: devmgmt:1562     - MainThread               - INFO - MQTT client state after exception: connected=True, state=1
May 12 17:35:40 python3[29330]: devmgmt:1217     - MainThread               - ERROR - mqtt: client is disconnected, rc: 7, The connection was lost.
May 12 17:35:40 python3[29330]: devmgmt:1217     - MainThread               - ERROR - mqtt: client is disconnected, rc: 7, The connection was lost.
May 12 17:35:41 python3[29330]: devmgmt:1227     - MainThread               - INFO - mqtt: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'354513599126954-1aa27f00bfdb-608a10c24009DM6319'
May 12 17:35:42 python3[29330]: devmgmt:1227     - MainThread               - INFO - mqtt: Received CONNACK (0, 0)
May 12 17:35:42 python3[29330]: devmgmt:1186     - MainThread               - INFO - mqtt: client is connected, rc: 0, No error.
May 12 17:35:42 python3[29330]: devmgmt:1368     - MainThread               -
